[package]
authors      = { workspace = true }
description  = "Webview bundle API for Tauri"
edition      = { workspace = true }
license      = { workspace = true }
links        = "wvb-tauri"
name         = "wvb-tauri"
repository   = { workspace = true }
rust-version = "1.85.0"
version      = "0.1.0"

[dependencies]
serde     = { workspace = true }
tauri     = { workspace = true, features = ["unstable"] }
thiserror = { workspace = true }
wvb       = { workspace = true, features = ["protocol", "protocol-local", "remote", "updater"] }

[build-dependencies]
tauri-plugin = { workspace = true, features = ["build"] }
