[package]
authors      = { workspace = true }
description  = "TBD"
edition      = { workspace = true }
license      = { workspace = true }
name         = "wvb-node"
publish      = false
repository   = { workspace = true }
rust-version = "1.85.0"
version      = "0.0.0"

[lib]
bench      = false
crate-type = ["cdylib"]
doctest    = false

[dependencies]
infer       = { workspace = true }
napi        = { workspace = true, features = ["napi8", "async"] }
napi-derive = { workspace = true }
thiserror   = { workspace = true }
tokio       = { workspace = true, features = ["fs", "io-util"] }
wvb         = { workspace = true, features = ["full"] }

[build-dependencies]
napi-build = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }

[lints.clippy]
module_inception = "allow"
